# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\df426\Documents\MCircus_GUI\Dialog_PatternOptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 179)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 13, 321, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.MergeThreshold_LB = QtWidgets.QLabel(self.gridLayoutWidget)
        self.MergeThreshold_LB.setObjectName("MergeThreshold_LB")
        self.gridLayout.addWidget(self.MergeThreshold_LB, 1, 0, 1, 1)
        self.MinInt_LB = QtWidgets.QLabel(self.gridLayoutWidget)
        self.MinInt_LB.setObjectName("MinInt_LB")
        self.gridLayout.addWidget(self.MinInt_LB, 0, 0, 1, 1)
        self.MinInt_SBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.MinInt_SBox.setDecimals(5)
        self.MinInt_SBox.setMinimum(1e-05)
        self.MinInt_SBox.setMaximum(0.9)
        self.MinInt_SBox.setSingleStep(1e-05)
        self.MinInt_SBox.setObjectName("MinInt_SBox")
        self.gridLayout.addWidget(self.MinInt_SBox, 0, 1, 1, 1)
        self.IntRatio_SBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.IntRatio_SBox.setObjectName("IntRatio_SBox")
        self.gridLayout.addWidget(self.IntRatio_SBox, 2, 1, 1, 1)
        self.MergeThreshold_SBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.MergeThreshold_SBox.setObjectName("MergeThreshold_SBox")
        self.gridLayout.addWidget(self.MergeThreshold_SBox, 1, 1, 1, 1)
        self.IntRatio_LB = QtWidgets.QLabel(self.gridLayoutWidget)
        self.IntRatio_LB.setObjectName("IntRatio_LB")
        self.gridLayout.addWidget(self.IntRatio_LB, 2, 0, 1, 1)
        self.SetOptions_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SetOptions_btn.setObjectName("SetOptions_btn")
        self.gridLayout.addWidget(self.SetOptions_btn, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.MergeThreshold_LB.setText(_translate("Dialog", "Merge Threshold (dalton)"))
        self.MinInt_LB.setText(_translate("Dialog", "Min Intensity (%)"))
        self.IntRatio_LB.setText(_translate("Dialog", "Intensity Ration (%)"))
        self.SetOptions_btn.setText(_translate("Dialog", "PushButton"))
