# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file "c:\Users\df426\Documents\MCircus_GUI\Ui\FilterDialog.ui"
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 126)
        self.SetFilter_btn = QtWidgets.QPushButton(Dialog)
        self.SetFilter_btn.setGeometry(QtCore.QRect(270, 90, 75, 23))
        self.SetFilter_btn.setObjectName("SetFilter_btn")
        self.SP_CBox = QtWidgets.QComboBox(Dialog)
        self.SP_CBox.setGeometry(QtCore.QRect(20, 40, 231, 22))
        self.SP_CBox.setObjectName("SP_CBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label.setObjectName("label")
        self.Filter_CBox = QtWidgets.QComboBox(Dialog)
        self.Filter_CBox.setGeometry(QtCore.QRect(20, 90, 231, 22))
        self.Filter_CBox.setObjectName("Filter_CBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SetFilter_btn.setText(_translate("Dialog", "Select"))
        self.label.setText(_translate("Dialog", "Spectra file"))
        self.label_2.setText(_translate("Dialog", "Filter"))
